results_dir: "results/mnist"
num_epochs: 20
batch_size: 32
latent_dim: 100
learning_rate_G: 0.0002
learning_rate_D: 0.0002
betas: [0.5, 0.999]
size_train_dataset: 10000
size_reference_dataset: 128
size_generated_dataset: 64
num_generated: 200